print("Created a repository on github.")
print("Creating a python file.")
print("--------------------------------")
print("Changing in local repo.")
print("--------------------------------")
print("Changing in remoteBranch.")
print("--------------------------------")
print("Changing in localBranch.")
