print("Created a python file using windows terminal.")
print("Opened the file in VsCode.")
print("Opened the file in Notepad. The command is 'notepad fileName.extension'.")
print("----------------------------------------------------------------------------")
print("Making changes after tracking the file in git.")
Print("Changing to check git diff.")
print("Changing after hard reset.")
print("----------------------------------------------------------------------------")
print("Changing in remote repo.")
print("Creating conflict on master branch.")
